### PR TITLE
CANVAS-47 - Reports: Display available Digital music reserves content

### PR DESCRIPTION
**Pull request by chern**

### CODE REVIEW

**Comment by maxpluez** [comment]
Codes look to me.
Tested UI looks like this:
Screenshot from 2020-08-20 13-26-05
One thing tho, after a search for term, classShortname with null also got searched up
Screenshot from 2020-08-20 13-27-18
Is this expected behavior?

**Comment by maxpluez** [comment]
Tested. All good!

**Comment by maxpluez** [comment]
I can see that after we expand the “No Shortname“ Tab we can see the term and srs. How about using something like <term>/<srs> in the title instead of “No Shortname“? I feel like it would be clearer.

**Comment by chern** [comment]
The way the database aggregates the data is that all records without a shortname is grouped under `null`, regardless of term and srs, so it wouldn’t be accurate to put a term/srs in the toggle name

**Pull request merged**
